# Generated by Django 3.2.18 on 2023-04-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=120, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='İstifadəçi adı')),
                ('surname', models.CharField(blank=True, max_length=40, null=True, verbose_name='İstifadəçi soyadı')),
                ('profil_image', models.ImageField(blank=True, null=True, upload_to='Doctor Profile Image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
