# Generated by Django 3.2.18 on 2023-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profil_image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile Image'),
        ),
    ]
