# Generated by Django 3.2.18 on 2023-04-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='follow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagram',
            name='follower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='login',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
