# Generated by Django 3.2.18 on 2023-04-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_instagram_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagram',
            name='login',
        ),
    ]
