# Generated by Django 3.2.18 on 2023-04-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_instagram_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='login',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
